// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"time"

	"github.com/google/uuid"
)

type Document struct {
	ID        uuid.UUID `json:"id"`
	Title     string    `json:"title"`
	OwnerID   uuid.UUID `json:"owner_id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type DocumentContent struct {
	DocumentID uuid.UUID `json:"document_id"`
	Content    []byte    `json:"content"`
	Version    int32     `json:"version"`
}

type DocumentPermission struct {
	ID              uuid.UUID `json:"id"`
	DocumentID      uuid.UUID `json:"document_id"`
	UserID          uuid.UUID `json:"user_id"`
	PermissionLevel string    `json:"permission_level"`
}

type DocumentVersion struct {
	ID              int32     `json:"id"`
	DocumentID      uuid.UUID `json:"document_id"`
	ContentSnapshot []byte    `json:"content_snapshot"`
	Version         int32     `json:"version"`
	CreatedAt       time.Time `json:"created_at"`
}

type User struct {
	ID           uuid.UUID `json:"id"`
	Username     string    `json:"username"`
	PasswordHash string    `json:"password_hash"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}
